language: node_js
node_js:
- '10'
- '9'
cache:
  directories:
  - node_modules
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.4.deb
  - sudo dpkg -i --force-confnew elasticsearch-6.2.4.deb
  - sudo /etc/init.d/elasticsearch start
  - until curl --silent -XGET --fail http://localhost:9200; do printf '.'; sleep 1; done
script:
  - yarn lint
  - yarn test
  - yarn compile
after_success:
  - yarn coverage
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    branch: master
    tags: true
    repo: guthega/elastic_receiver
    node: '10'
